# Site settings
title: Tushar Gautam
email: "0mean1sigma[at]gmail.com"
description: "What I cannot create, I do not understand - Richard Feynman" 
baseurl: ""
url: "http://tgautam03.github.io"
#twitter_username:
github_username:  tgautam03

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
