# Site settings
title: N Questions
email: "[first_name(without caps)].[last_name(without caps)][at]utah.edu"
description: "Any problem can be divided into N simple questions"
baseurl: ""
url: "http://tgautam03.github.io"
#twitter_username:
github_username:  tgautam03

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
